name: kucing
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  stroke_text: any
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/flutter_logo.png" # Ganti dengan lokasi ikon Anda
  adaptive_icon_background: "#ffffff" # Untuk ikon adaptif Android

flutter:
  uses-material-design: true
  fonts:
    - family: Bold Condensed
      fonts:
        - asset: assets/fonts/Roboto-BoldCondensed.ttf
    - family: Regular
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
    - family: Light
      fonts:
        - asset: assets/fonts/Roboto-Light.ttf
  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/fonts/
    - assets/images/
    - assets/images/ekspresi/
    - assets/images/doDont/
    - assets/images/fnb/

